stages:
  - publish

publishing:
  stage: publish
  tags:
    - moreillon
  script:
    - npm install
    - npm run build
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm publish
